---
# - name: Run common
#   import_playbook: common.yml

- name: Deploy pi with Ansible
  hosts: pi
  become: yes

  # vars:
  #   nvm_install_script_version: "0.33.11"
  #   nvm_node_version: "4.1.1"
  #   nvm_install_globally: ['peerflix']
  #   terraform_ver: "0.12.20"

  vars:
    prometheus_targets:
      node:
      - targets:
        - localhost:9100
        labels:
          env: localhost

  roles:
    - ohmyzsh
    - cloudalchemy.node-exporter
    # - cloudalchemy.blackbox-exporter
    - cloudalchemy.prometheus
    # - cloudalchemy.alertmanager
    # - cloudalchemy.grafana
    - common-pi

  tasks:
    - name : list users to apply oh-my-zsh
      shell: "getent passwd {1000..1010} | awk -F: '$3 {print $1}'"
      register: users

    - name: Fix Docker execution without sudo #Issue #7
      shell: "users=$( getent passwd {1000..1010} | awk -F: '$3 {print $1}' );for user in $users; do sudo usermod -a -G docker $user; done"