---
# - name: Run common
#   import_playbook: common.yml

- name: Deploy pi with Ansible
  hosts: pi
  become: yes

  vars:
  #Static IP
    # custom_ip: "192.168.0.50"
    # custom_gateway_ip: "192.168.0.1"
    # custom_dns_server: "8.8.8.8,1.1.1.1,208.67.222.222"
  # Prometheus
    # prometheus_targets:
    #   node:
    #   - targets:
    #     - localhost:9100
    #     labels:
    #       env: localhost

  roles:
    - bihealth.python3
    - ohmyzsh
    - cloudalchemy.node-exporter
    # - cloudalchemy.blackbox-exporter
    # - cloudalchemy.prometheus
    # - cloudalchemy.alertmanager
    # - cloudalchemy.grafana
    - common-pi
    - docker
    # - static-ip

  tasks:
    - name : list users to apply oh-my-zsh
      shell: "getent passwd {1000..1010} | awk -F: '$3 {print $1}'"
      register: users

    - name: Fix Docker execution without sudo #Issue #7
      shell: "users=$( getent passwd {1000..1010} | awk -F: '$3 {print $1}' );for user in $users; do sudo usermod -a -G docker $user; done"